### ISSUE TITLE
Port命令的主动模式实现逻辑有问题

### ISSUE THREAD

**Issue by ikvm** [kerryjiang/SuperSocket.FtpServer#1]

**Comment by kerryjiang** [comment]
Could you describe more about the detail?

**Comment by ikvm** [comment]
the Active mode is connect, and not listen??

**Comment by kerryjiang** [comment]
Port means the data port is requested by the client. The Pasv means let server side decide which port should be used as data port. Because of the firewall issue, the second is used more widely.
