### ISSUE TITLE
No user setting file was not defined!

### ISSUE THREAD

**Issue by kincjf** [kerryjiang/SuperSocket.FtpServer#3]
Hi
I read README and setup as description!

![folder](http://farm4.staticflickr.com/3720/19463861256_3aa91ce651_b.jpg)
in folder(root)

![folder/Config](http://farm4.staticflickr.com/3726/19494270811_00fc942902_b.jpg)
in folder(/Config)

![SuperSocket.SocketService.exe.config](http://farm1.staticflickr.com/465/19303789289_d01a4eab68_b.jpg)
SuperSocket.SocketService.exe.config

![Config/FtpUser.xml](http://farm1.staticflickr.com/474/19302350388_de41b126c7_b.jpg)
Config/FtpUser.xml

After setup, but failed to run
In err.log - [6964] ERROR SuperSocketFTP - No user setting file was not defined!
                 [6964] ERROR DefaultBootstrap - Failed to setup server instance!

and try it couple of times. but it was failed..

How Can it run? Thanks to explain in details.

best regards
Seonho

**Comment by kerryjiang** [comment]
Sorry, there should be a configuration attribute for the server node:
userSetting="Config\FtpUser.xml"

I'll update the document ASAP.
